name: check upstream patches

on: [pull_request]

env:
  DOWNLOAD: ".download"
  MAKEFLAGS: "CC=gcc-11"
  UNPACKED: ".unpacked"

jobs:
  patch_chk_job:
    runs-on:
      - self-hosted
      - builder
      - Ubuntu
    container: ubuntu:22.04
    name: Patches Check
    steps:
    - name: Get commits count
      run: |
        COMMIT_CNT=$((${{ github.event.pull_request.commits }}+1))
        echo "COMMIT_CNT=${COMMIT_CNT}" >> $GITHUB_ENV

    - name: Install deps
      run: |
        apt-get -q=2 update
        apt-get -q=2 install \
          bc \
          bison \
          build-essential \
          coccinelle \
          flex \
          libelf-dev \
          libpython2.7 \
          libsqlite3-dev \
          libssl-dev \
          python3 \
          python3-git \
          python3-ply

    - name: Check out repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.COMMIT_CNT }}

    # actions/checkout@v2 does set safe.directory but, empirically,
    # the setting appears to be temporary
    - name: Set safe.directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout and Build Sparse
      run: |
        git clone --quiet https://git.kernel.org/pub/scm/devel/sparse/sparse.git || git clone --quiet https://kernel.googlesource.com/pub/scm/devel/sparse/sparse.git
        # Revision of master branch with 'unreplaced' branch mergep
        (cd sparse && git checkout ce1a6720f69e)
        make -j"$(nproc)" -C ./sparse

    - name: Checkout and Build Smatch
      run: |
        git clone --quiet --branch 1.73 --depth 1 https://github.com/error27/smatch
        make -j"$(nproc)" -C ./smatch

    - name: 64-bit Configure & Build Kernel
      run: |
        cp -p .github/deps/local_defconfig ./arch/x86/configs/
        make -s local_defconfig
        make -s -j"$(nproc)"

    - name: Run compile check scripts for 64-bit
      run: |
        cp -p .github/deps/compile_check.sh ./
        export PATH=$PATH:`pwd`/${{ env.UNPACKED }}/usr/bin
        ./compile_check.sh ${{ github.event.pull_request.commits }}

    - name: Run check scripts
      run: |
        cp -p .github/deps/commits_check.sh ./
        cp -p .github/deps/xmastree.py ./
        export PATH=$PATH:`pwd`/${{ env.UNPACKED }}/usr/bin
        ./commits_check.sh ${{ github.event.pull_request.commits }}

    - name: 32-bit Configure & Build Kernel
      run: |
        make -s clean -j"$(nproc)"
        echo "# CONFIG_64BIT is not set" >> ./arch/x86/configs/local_defconfig
        make -s local_defconfig
        make -s -j"$(nproc)"

    - name: Run compile check scripts for 32-bit
      run: |
        cp -p .github/deps/compile_check.sh ./
        export PATH=$PATH:`pwd`/${{ env.UNPACKED }}/usr/bin
        ./compile_check.sh ${{ github.event.pull_request.commits }}

    - name: Configure with ipv6 disabled & Build Kernel
      run: |
        make -s clean -j"$(nproc)"
        sed -i 's/# CONFIG_64BIT.*/CONFIG_64BIT=y/g' ./arch/x86/configs/local_defconfig
        echo "# CONFIG_IPV6 is not set" >> ./arch/x86/configs/local_defconfig
        make -s local_defconfig
        make -s -j"$(nproc)"

    - name: Run compile check scripts for CONFIG_IPV6 disabled
      run: |
        cp -p .github/deps/compile_check.sh ./
        export PATH=$PATH:`pwd`/${{ env.UNPACKED }}/usr/bin
        ./compile_check.sh ${{ github.event.pull_request.commits }}

    - name: Cleanup afterwards
      if: always()
      run: find -delete
